services:
  rmqbe:
    build: ..
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      mongo:
        condition: service_started

  mongo:
    image: mongo:8.2.2
    ports:
      - 127.0.0.1:27017:27017

  rabbitmq:
    image: rabbitmq:4.2.1-management-alpine
    ports:
      - 127.0.0.1:1883:1883
      - 127.0.0.1:5672:5672
      - 127.0.0.1:8883:8883
      - 127.0.0.1:15672:15672
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
